version: '3.9'
services:
  django_app:
    build: .
    volumes:
      - media_vol:/app/media
    ports:
      - "8000:8000"
  telegram_bot:
    build: .
    env_file:
      - .env
    volumes:
      - media_vol:/app/media
    command: ["python", "main_bot.py"]
    depends_on:
      - django_app
    


  nginx:
    build: ./nginx
    volumes:
      - media_vol:/app/media
    ports:
      - "80:80"
    depends_on:
      - django_app

  
      
volumes:
  media_vol:



