# Generated by Django 4.2.7 on 2024-01-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_avansuser_user_id_alter_avansuser_avans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avansuser',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
